# Form implementation generated from reading ui file 'home_panel.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_doc_panel(object):
    def setupUi(self, doc_panel):
        doc_panel.setObjectName("doc_panel")
        doc_panel.resize(1165, 1014)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/san_rafael3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        doc_panel.setWindowIcon(icon)
        doc_panel.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 4, 53, 255), stop:1 rgba(46, 90, 136, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=doc_panel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QFrame(parent=self.frame)
        self.header.setMinimumSize(QtCore.QSize(0, 100))
        self.header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header.setStyleSheet("background-color: transparent;")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.header)
        self.frame_2.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_menu = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu.sizePolicy().hasHeightForWidth())
        self.btn_menu.setSizePolicy(sizePolicy)
        self.btn_menu.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(16, 1, 186);\n"
"}QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"    color: white;\n"
"    font: 63 16pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 116, 210);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/button_menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu.setIcon(icon1)
        self.btn_menu.setIconSize(QtCore.QSize(60, 60))
        self.btn_menu.setObjectName("btn_menu")
        self.verticalLayout_3.addWidget(self.btn_menu, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 32pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.header)
        self.main_body = QtWidgets.QFrame(parent=self.frame)
        self.main_body.setStyleSheet("background-color: transparent;")
        self.main_body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(parent=self.main_body)
        self.sidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.sidebar.setStyleSheet("background-color:rgb(0, 0, 97)")
        self.sidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(parent=self.sidebar)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setToolTipDuration(0)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAccessibleDescription("")
        self.label_3.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"border: 2px solid white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.btn_view = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view.sizePolicy().hasHeightForWidth())
        self.btn_view.setSizePolicy(sizePolicy)
        self.btn_view.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/document_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_view.setIcon(icon2)
        self.btn_view.setIconSize(QtCore.QSize(50, 50))
        self.btn_view.setObjectName("btn_view")
        self.verticalLayout_6.addWidget(self.btn_view)
        self.btn_accounts = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_accounts.sizePolicy().hasHeightForWidth())
        self.btn_accounts.setSizePolicy(sizePolicy)
        self.btn_accounts.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 16pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/account_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_accounts.setIcon(icon3)
        self.btn_accounts.setIconSize(QtCore.QSize(50, 50))
        self.btn_accounts.setObjectName("btn_accounts")
        self.verticalLayout_6.addWidget(self.btn_accounts)
        self.btn_tbledit = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tbledit.sizePolicy().hasHeightForWidth())
        self.btn_tbledit.setSizePolicy(sizePolicy)
        self.btn_tbledit.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 15pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/row_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_tbledit.setIcon(icon4)
        self.btn_tbledit.setIconSize(QtCore.QSize(50, 50))
        self.btn_tbledit.setObjectName("btn_tbledit")
        self.verticalLayout_6.addWidget(self.btn_tbledit)
        self.btn_guide = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_guide.sizePolicy().hasHeightForWidth())
        self.btn_guide.setSizePolicy(sizePolicy)
        self.btn_guide.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 15pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/about_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_guide.setIcon(icon5)
        self.btn_guide.setIconSize(QtCore.QSize(50, 50))
        self.btn_guide.setObjectName("btn_guide")
        self.verticalLayout_6.addWidget(self.btn_guide)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("border: 2px solid white;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.btn_doccontents = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_doccontents.sizePolicy().hasHeightForWidth())
        self.btn_doccontents.setSizePolicy(sizePolicy)
        self.btn_doccontents.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/edit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_doccontents.setIcon(icon6)
        self.btn_doccontents.setIconSize(QtCore.QSize(50, 50))
        self.btn_doccontents.setObjectName("btn_doccontents")
        self.verticalLayout_6.addWidget(self.btn_doccontents)
        self.btn_prices = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prices.sizePolicy().hasHeightForWidth())
        self.btn_prices.setSizePolicy(sizePolicy)
        self.btn_prices.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 16pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 64);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(128, 183, 255);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../doc_processing_panel/icons/price_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_prices.setIcon(icon7)
        self.btn_prices.setIconSize(QtCore.QSize(50, 50))
        self.btn_prices.setObjectName("btn_prices")
        self.verticalLayout_6.addWidget(self.btn_prices)
        self.none = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.none.sizePolicy().hasHeightForWidth())
        self.none.setSizePolicy(sizePolicy)
        self.none.setStyleSheet("")
        self.none.setText("")
        self.none.setIconSize(QtCore.QSize(50, 50))
        self.none.setObjectName("none")
        self.verticalLayout_6.addWidget(self.none)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.sidebar)
        self.body = QtWidgets.QFrame(parent=self.main_body)
        self.body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.body)
        self.stackedWidget.setStyleSheet("#stackedWidget{border: 2px solid white;}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.accounts = QtWidgets.QWidget()
        self.accounts.setObjectName("accounts")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.accounts)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_20 = QtWidgets.QFrame(parent=self.accounts)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_64 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_64.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;\n"
"")
        self.label_64.setObjectName("label_64")
        self.verticalLayout_21.addWidget(self.label_64)
        self.verticalLayout_20.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_22)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_24)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.tbl_accounts = QtWidgets.QTableWidget(parent=self.frame_29)
        self.tbl_accounts.setGeometry(QtCore.QRect(20, 0, 201, 731))
        self.tbl_accounts.setStyleSheet("background-color: white;")
        self.tbl_accounts.setObjectName("tbl_accounts")
        self.tbl_accounts.setColumnCount(2)
        self.tbl_accounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts.setHorizontalHeaderItem(1, item)
        self.user_delete = QtWidgets.QPushButton(parent=self.frame_29)
        self.user_delete.setGeometry(QtCore.QRect(270, 80, 155, 37))
        self.user_delete.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.user_delete.setObjectName("user_delete")
        self.user_verify = QtWidgets.QPushButton(parent=self.frame_29)
        self.user_verify.setGeometry(QtCore.QRect(270, 130, 155, 37))
        self.user_verify.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.user_verify.setObjectName("user_verify")
        self.ref_table = QtWidgets.QPushButton(parent=self.frame_29)
        self.ref_table.setGeometry(QtCore.QRect(270, 230, 155, 37))
        self.ref_table.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.ref_table.setObjectName("ref_table")
        self.user_unverify = QtWidgets.QPushButton(parent=self.frame_29)
        self.user_unverify.setGeometry(QtCore.QRect(270, 180, 155, 37))
        self.user_unverify.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.user_unverify.setObjectName("user_unverify")
        self.tbl_accounts_2 = QtWidgets.QTableWidget(parent=self.frame_29)
        self.tbl_accounts_2.setGeometry(QtCore.QRect(600, 0, 301, 731))
        self.tbl_accounts_2.setStyleSheet("background-color: white;")
        self.tbl_accounts_2.setObjectName("tbl_accounts_2")
        self.tbl_accounts_2.setColumnCount(3)
        self.tbl_accounts_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts_2.setHorizontalHeaderItem(2, item)
        self.ref_tabletransaction = QtWidgets.QPushButton(parent=self.frame_29)
        self.ref_tabletransaction.setGeometry(QtCore.QRect(920, 60, 155, 37))
        self.ref_tabletransaction.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.ref_tabletransaction.setObjectName("ref_tabletransaction")
        self.edit_accounts = QtWidgets.QPushButton(parent=self.frame_29)
        self.edit_accounts.setGeometry(QtCore.QRect(270, 280, 155, 37))
        self.edit_accounts.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.edit_accounts.setObjectName("edit_accounts")
        self.horizontalLayout_10.addWidget(self.frame_29)
        self.horizontalLayout_9.addWidget(self.frame_24)
        self.horizontalLayout_8.addWidget(self.frame_26)
        self.horizontalLayout_7.addWidget(self.frame_25)
        self.verticalLayout_20.addWidget(self.frame_22)
        self.verticalLayout_19.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.accounts)
        self.edit_contents = QtWidgets.QWidget()
        self.edit_contents.setObjectName("edit_contents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.edit_contents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_11 = QtWidgets.QFrame(parent=self.edit_contents)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_40 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_40.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;\n"
"")
        self.label_40.setObjectName("label_40")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_40)
        self.label_41 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_41.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_41.setObjectName("label_41")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_41)
        self.line_editref = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editref.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editref.setText("")
        self.line_editref.setObjectName("line_editref")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editref)
        self.label_42 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_42.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_42.setObjectName("label_42")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_42)
        self.line_editname = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editname.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editname.setText("")
        self.line_editname.setObjectName("line_editname")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editname)
        self.label_43 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_43.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_43.setObjectName("label_43")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_43)
        self.line_editage = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editage.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editage.setText("")
        self.line_editage.setObjectName("line_editage")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editage)
        self.label_45 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_45.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_45.setObjectName("label_45")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_45)
        self.line_editsex = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editsex.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editsex.setText("")
        self.line_editsex.setObjectName("line_editsex")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editsex)
        self.label_44 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_44.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_44.setObjectName("label_44")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_44)
        self.cBox_doctype = QtWidgets.QComboBox(parent=self.frame_11)
        self.cBox_doctype.setStyleSheet("\n"
"#cBox_doctype QAbstractItemView{\n"
"selection-background-color: rgb(72, 82, 101);\n"
"}\n"
"#cBox_doctype::drop-down{\n"
"border: 0px;\n"
"}\n"
"QComboBox{\n"
"border: 4px;\n"
"color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"}\n"
"#cBox_doctype:on{\n"
"border: 4px solid rgb(72, 82, 101);\n"
"}\n"
"#cBox_doctype QListView{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cBox_doctype.setObjectName("cBox_doctype")
        self.cBox_doctype.addItem("")
        self.cBox_doctype.addItem("")
        self.cBox_doctype.addItem("")
        self.cBox_doctype.addItem("")
        self.cBox_doctype.addItem("")
        self.cBox_doctype.addItem("")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cBox_doctype)
        self.label_46 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_46.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_46.setObjectName("label_46")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_46)
        self.line_editbirthplace = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editbirthplace.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editbirthplace.setText("")
        self.line_editbirthplace.setObjectName("line_editbirthplace")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editbirthplace)
        self.label_47 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_47.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_47.setObjectName("label_47")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_48.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_48.setObjectName("label_48")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_48)
        self.line_editbusinessname = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editbusinessname.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editbusinessname.setText("")
        self.line_editbusinessname.setObjectName("line_editbusinessname")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editbusinessname)
        self.label_49 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_49.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_49.setObjectName("label_49")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_49)
        self.line_editbusinessaddress = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editbusinessaddress.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editbusinessaddress.setText("")
        self.line_editbusinessaddress.setObjectName("line_editbusinessaddress")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editbusinessaddress)
        self.label_51 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_51.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_51.setObjectName("label_51")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_51)
        self.line_editcitizenship = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editcitizenship.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editcitizenship.setText("")
        self.line_editcitizenship.setObjectName("line_editcitizenship")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editcitizenship)
        self.label_52 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_52.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_52.setObjectName("label_52")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_52)
        self.line_editcivilstatus = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editcivilstatus.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editcivilstatus.setText("")
        self.line_editcivilstatus.setObjectName("line_editcivilstatus")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editcivilstatus)
        self.label_50 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_50.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_50.setObjectName("label_50")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_50)
        self.cBox_purpose = QtWidgets.QComboBox(parent=self.frame_11)
        self.cBox_purpose.setStyleSheet("\n"
"#cBox_purpose QAbstractItemView{\n"
"selection-background-color: rgb(72, 82, 101);\n"
"}\n"
"#cBox_purpose::drop-down{\n"
"border: 0px;\n"
"}\n"
"QComboBox{\n"
"border: 4px;\n"
"color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"}\n"
"#cBox_purpose:on{\n"
"border: 4px solid rgb(72, 82, 101);\n"
"}\n"
"#cBox_purpose QListView{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cBox_purpose.setObjectName("cBox_purpose")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.cBox_purpose.addItem("")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cBox_purpose)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_15.setStyleSheet("background-color: transparent;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_4.setSpacing(200)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edit_row = QtWidgets.QPushButton(parent=self.frame_15)
        self.edit_row.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.edit_row.setObjectName("edit_row")
        self.horizontalLayout_4.addWidget(self.edit_row)
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_15)
        self.line_editbirthdate = QtWidgets.QLineEdit(parent=self.frame_11)
        self.line_editbirthdate.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_editbirthdate.setText("")
        self.line_editbirthdate.setObjectName("line_editbirthdate")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editbirthdate)
        self.verticalLayout_13.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.edit_contents)
        self.guide = QtWidgets.QWidget()
        self.guide.setObjectName("guide")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.guide)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_13 = QtWidgets.QFrame(parent=self.guide)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_66 = QtWidgets.QLabel(parent=self.frame_27)
        self.label_66.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;\n"
"")
        self.label_66.setObjectName("label_66")
        self.verticalLayout_24.addWidget(self.label_66)
        self.verticalLayout_23.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_67 = QtWidgets.QLabel(parent=self.frame_28)
        self.label_67.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;\n"
"")
        self.label_67.setObjectName("label_67")
        self.verticalLayout_22.addWidget(self.label_67)
        self.verticalLayout_23.addWidget(self.frame_28, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_68 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_68.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;\n"
"")
        self.label_68.setObjectName("label_68")
        self.verticalLayout_25.addWidget(self.label_68, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_23.addWidget(self.frame_23)
        self.verticalLayout_15.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.guide)
        self.doc_prices = QtWidgets.QWidget()
        self.doc_prices.setObjectName("doc_prices")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.doc_prices)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtWidgets.QFrame(parent=self.doc_prices)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.formLayout = QtWidgets.QFormLayout(self.frame_8)
        self.formLayout.setObjectName("formLayout")
        self.label_37 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_37.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_37)
        self.label_36 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_36.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_36.setObjectName("label_36")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_36)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_8)
        self.lineEdit.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_38 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_38.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_38)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_8)
        self.lineEdit_2.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.label_39 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_39.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_39)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_8)
        self.lineEdit_3.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_16.setStyleSheet("background-color: transparent;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_5.setSpacing(200)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edit_price = QtWidgets.QPushButton(parent=self.frame_16)
        self.edit_price.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.edit_price.setObjectName("edit_price")
        self.horizontalLayout_5.addWidget(self.edit_price)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_16)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.doc_prices)
        self.doc_contents = QtWidgets.QWidget()
        self.doc_contents.setObjectName("doc_contents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.doc_contents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_12 = QtWidgets.QFrame(parent=self.doc_contents)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_53 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_53.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 26pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_53.setObjectName("label_53")
        self.verticalLayout_18.addWidget(self.label_53)
        self.verticalLayout_17.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_18)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_54 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_54.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_54.setObjectName("label_54")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_54)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_4.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_55 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_55.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_55.setObjectName("label_55")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_55)
        self.line_captain = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_captain.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_captain.setText("")
        self.line_captain.setObjectName("line_captain")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_captain)
        self.label_57 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_57.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_57.setObjectName("label_57")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_57)
        self.line_chsw = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_chsw.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_chsw.setText("")
        self.line_chsw.setObjectName("line_chsw")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_chsw)
        self.label_58 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_58.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_58.setObjectName("label_58")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_58)
        self.line_livelihood = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_livelihood.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_livelihood.setText("")
        self.line_livelihood.setObjectName("line_livelihood")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_livelihood)
        self.label_60 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_60.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_60.setObjectName("label_60")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_60)
        self.line_ceb = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_ceb.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_ceb.setText("")
        self.line_ceb.setObjectName("line_ceb")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ceb)
        self.label_59 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_59.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_59.setObjectName("label_59")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_59)
        self.line_cpo = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_cpo.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_cpo.setText("")
        self.line_cpo.setObjectName("line_cpo")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_cpo)
        self.label_61 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_61.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_61.setObjectName("label_61")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_61)
        self.line_css = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_css.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_css.setText("")
        self.line_css.setObjectName("line_css")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_css)
        self.label_62 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_62.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_62.setObjectName("label_62")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_62)
        self.line_csyd = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_csyd.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_csyd.setText("")
        self.line_csyd.setObjectName("line_csyd")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_csyd)
        self.label_56 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_56.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_56.setObjectName("label_56")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_56)
        self.line_cfcp = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_cfcp.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_cfcp.setText("")
        self.line_cfcp.setObjectName("line_cfcp")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_cfcp)
        self.label_63 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_63.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: transparent;")
        self.label_63.setObjectName("label_63")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_63)
        self.line_skchairman = QtWidgets.QLineEdit(parent=self.frame_18)
        self.line_skchairman.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_skchairman.setText("")
        self.line_skchairman.setObjectName("line_skchairman")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_skchairman)
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_19.setStyleSheet("background-color: transparent;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setSpacing(200)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edit_doccontent = QtWidgets.QPushButton(parent=self.frame_19)
        self.edit_doccontent.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.edit_doccontent.setObjectName("edit_doccontent")
        self.horizontalLayout_6.addWidget(self.edit_doccontent)
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_19)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.verticalLayout_16.addWidget(self.frame_14)
        self.verticalLayout_14.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.doc_contents)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_30 = QtWidgets.QFrame(parent=self.page)
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tbl_accView = QtWidgets.QTableWidget(parent=self.frame_31)
        self.tbl_accView.setStyleSheet("background-color: white;")
        self.tbl_accView.setObjectName("tbl_accView")
        self.tbl_accView.setColumnCount(9)
        self.tbl_accView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accView.setHorizontalHeaderItem(8, item)
        self.horizontalLayout_12.addWidget(self.tbl_accView)
        self.horizontalLayout_11.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_30)
        self.frame_32.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_32.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_33.setStyleSheet("#frame_33{border: 2px solid white;}")
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_10.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_27.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_11.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_27.addWidget(self.label_11)
        self.edit_email = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_email.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_email.setObjectName("edit_email")
        self.verticalLayout_27.addWidget(self.edit_email)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_12.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_27.addWidget(self.label_12)
        self.edit_password = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_password.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_password.setObjectName("edit_password")
        self.verticalLayout_27.addWidget(self.edit_password)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_13.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_27.addWidget(self.label_13)
        self.edit_uname = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_uname.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_uname.setObjectName("edit_uname")
        self.verticalLayout_27.addWidget(self.edit_uname)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_14.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_27.addWidget(self.label_14)
        self.edit_usex = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_usex.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_usex.setObjectName("edit_usex")
        self.verticalLayout_27.addWidget(self.edit_usex)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_17.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_27.addWidget(self.label_17)
        self.edit_uaddress = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_uaddress.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_uaddress.setObjectName("edit_uaddress")
        self.verticalLayout_27.addWidget(self.edit_uaddress)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_15.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_27.addWidget(self.label_15)
        self.edit_ubday = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_ubday.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_ubday.setObjectName("edit_ubday")
        self.verticalLayout_27.addWidget(self.edit_ubday)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_18.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_27.addWidget(self.label_18)
        self.edit_ubplace = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_ubplace.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_ubplace.setObjectName("edit_ubplace")
        self.verticalLayout_27.addWidget(self.edit_ubplace)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_16.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_27.addWidget(self.label_16)
        self.edit_ucstatus = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_ucstatus.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_ucstatus.setObjectName("edit_ucstatus")
        self.verticalLayout_27.addWidget(self.edit_ucstatus)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_19.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_27.addWidget(self.label_19)
        self.edit_ucitizenship = QtWidgets.QLineEdit(parent=self.frame_33)
        self.edit_ucitizenship.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.edit_ucitizenship.setObjectName("edit_ucitizenship")
        self.verticalLayout_27.addWidget(self.edit_ucitizenship)
        self.edit_user = QtWidgets.QPushButton(parent=self.frame_33)
        self.edit_user.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.edit_user.setObjectName("edit_user")
        self.verticalLayout_27.addWidget(self.edit_user)
        self.refresh_edittabel = QtWidgets.QPushButton(parent=self.frame_33)
        self.refresh_edittabel.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.refresh_edittabel.setObjectName("refresh_edittabel")
        self.verticalLayout_27.addWidget(self.refresh_edittabel)
        self.horizontalLayout_13.addWidget(self.frame_33)
        self.horizontalLayout_11.addWidget(self.frame_32)
        self.verticalLayout_26.addWidget(self.frame_30)
        self.stackedWidget.addWidget(self.page)
        self.tbl_view = QtWidgets.QWidget()
        self.tbl_view.setObjectName("tbl_view")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tbl_view)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_5 = QtWidgets.QFrame(parent=self.tbl_view)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line_searchbar = QtWidgets.QLineEdit(parent=self.frame_6)
        self.line_searchbar.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_searchbar.setObjectName("line_searchbar")
        self.verticalLayout_9.addWidget(self.line_searchbar)
        self.tbl_forview = QtWidgets.QTableWidget(parent=self.frame_6)
        self.tbl_forview.setStyleSheet("background-color: white;")
        self.tbl_forview.setObjectName("tbl_forview")
        self.tbl_forview.setColumnCount(17)
        self.tbl_forview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_forview.setHorizontalHeaderItem(16, item)
        self.verticalLayout_9.addWidget(self.tbl_forview)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 357))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 357))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_12.setSpacing(20)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_create = QtWidgets.QPushButton(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create.sizePolicy().hasHeightForWidth())
        self.btn_create.setSizePolicy(sizePolicy)
        self.btn_create.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"border-radius:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout_12.addWidget(self.btn_create)
        self.btn_filedir = QtWidgets.QPushButton(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_filedir.sizePolicy().hasHeightForWidth())
        self.btn_filedir.setSizePolicy(sizePolicy)
        self.btn_filedir.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.btn_filedir.setObjectName("btn_filedir")
        self.verticalLayout_12.addWidget(self.btn_filedir)
        self.btn_delete = QtWidgets.QPushButton(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"border-radius:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_12.addWidget(self.btn_delete)
        self.btn_refresh = QtWidgets.QPushButton(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 18pt \"Roboto Medium\";\n"
"border-radius:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.btn_refresh.setObjectName("btn_refresh")
        self.verticalLayout_12.addWidget(self.btn_refresh)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_9.setStyleSheet("#frame_9{border: 2px solid white;}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_9)
        self.formLayout_2.setContentsMargins(9, 9, 9, 9)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_4.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_5.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_5)
        self.line_ref = QtWidgets.QLineEdit(parent=self.frame_9)
        self.line_ref.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_ref.setObjectName("line_ref")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ref)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_6.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_6)
        self.line_req = QtWidgets.QLineEdit(parent=self.frame_9)
        self.line_req.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Helvetica Neue\";\n"
"    background-color: #1974D2;\n"
"border: none;")
        self.line_req.setObjectName("line_req")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_req)
        self.btn_editreq = QtWidgets.QPushButton(parent=self.frame_9)
        self.btn_editreq.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: rgb(25, 116, 210);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Roboto Medium\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 143, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.btn_editreq.setObjectName("btn_editreq")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btn_editreq)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.tbl_view)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.body)
        self.verticalLayout_2.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.frame)
        doc_panel.setCentralWidget(self.centralwidget)

        self.retranslateUi(doc_panel)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(doc_panel)

    def retranslateUi(self, doc_panel):
        _translate = QtCore.QCoreApplication.translate
        doc_panel.setWindowTitle(_translate("doc_panel", "Document Processing Panel"))
        self.btn_menu.setText(_translate("doc_panel", "MENU"))
        self.label.setText(_translate("doc_panel", "Document Processing Panel"))
        self.label_3.setText(_translate("doc_panel", "Main Functions"))
        self.btn_view.setText(_translate("doc_panel", "View Table          "))
        self.btn_accounts.setText(_translate("doc_panel", "Manage Accounts "))
        self.btn_tbledit.setText(_translate("doc_panel", "Edit Row Contents   "))
        self.btn_guide.setText(_translate("doc_panel", "About Software       "))
        self.label_2.setText(_translate("doc_panel", "Kiosk Edit Functions"))
        self.btn_doccontents.setText(_translate("doc_panel", "Document Contents"))
        self.btn_prices.setText(_translate("doc_panel", "Document Prices  "))
        self.label_64.setText(_translate("doc_panel", "Verifications and Transactions"))
        item = self.tbl_accounts.horizontalHeaderItem(0)
        item.setText(_translate("doc_panel", "Email"))
        item = self.tbl_accounts.horizontalHeaderItem(1)
        item.setText(_translate("doc_panel", "Verification Status"))
        self.user_delete.setText(_translate("doc_panel", "Delete User"))
        self.user_verify.setText(_translate("doc_panel", "Verify"))
        self.ref_table.setText(_translate("doc_panel", "Refresh Table"))
        self.user_unverify.setText(_translate("doc_panel", "Unverify"))
        item = self.tbl_accounts_2.horizontalHeaderItem(0)
        item.setText(_translate("doc_panel", "Name"))
        item = self.tbl_accounts_2.horizontalHeaderItem(1)
        item.setText(_translate("doc_panel", "Requested Doc"))
        item = self.tbl_accounts_2.horizontalHeaderItem(2)
        item.setText(_translate("doc_panel", "Price"))
        self.ref_tabletransaction.setText(_translate("doc_panel", "Refresh Table"))
        self.edit_accounts.setText(_translate("doc_panel", "Edit Accounts"))
        self.label_40.setText(_translate("doc_panel", "Edit Row Contents"))
        self.label_41.setText(_translate("doc_panel", "Reference #:"))
        self.line_editref.setPlaceholderText(_translate("doc_panel", "Enter Reference # here to autofill"))
        self.label_42.setText(_translate("doc_panel", "Name:"))
        self.line_editname.setPlaceholderText(_translate("doc_panel", "Firstname M.I. Lastname"))
        self.label_43.setText(_translate("doc_panel", "Age:"))
        self.line_editage.setPlaceholderText(_translate("doc_panel", "Age"))
        self.label_45.setText(_translate("doc_panel", "Sex:"))
        self.line_editsex.setPlaceholderText(_translate("doc_panel", "Male or Female"))
        self.label_44.setText(_translate("doc_panel", "Document Type:"))
        self.cBox_doctype.setItemText(0, _translate("doc_panel", "Click here to Select"))
        self.cBox_doctype.setItemText(1, _translate("doc_panel", "Business Permit"))
        self.cBox_doctype.setItemText(2, _translate("doc_panel", "Indigency"))
        self.cBox_doctype.setItemText(3, _translate("doc_panel", "Certificate for First Time Job Seeker"))
        self.cBox_doctype.setItemText(4, _translate("doc_panel", "Barangay Clearance"))
        self.cBox_doctype.setItemText(5, _translate("doc_panel", "First Time Job Seeker"))
        self.label_46.setText(_translate("doc_panel", "Birthplace:"))
        self.line_editbirthplace.setPlaceholderText(_translate("doc_panel", "Birthplace"))
        self.label_47.setText(_translate("doc_panel", "Birthdate:"))
        self.label_48.setText(_translate("doc_panel", "Business Name:"))
        self.line_editbusinessname.setPlaceholderText(_translate("doc_panel", "Business Name"))
        self.label_49.setText(_translate("doc_panel", "Business Address:"))
        self.line_editbusinessaddress.setPlaceholderText(_translate("doc_panel", "Business Address"))
        self.label_51.setText(_translate("doc_panel", "Citizenship:"))
        self.line_editcitizenship.setPlaceholderText(_translate("doc_panel", "Citizenship"))
        self.label_52.setText(_translate("doc_panel", "Civil Status:"))
        self.line_editcivilstatus.setPlaceholderText(_translate("doc_panel", "Civil Status"))
        self.label_50.setText(_translate("doc_panel", "Purpose:"))
        self.cBox_purpose.setItemText(0, _translate("doc_panel", "Click here to Select"))
        self.cBox_purpose.setItemText(1, _translate("doc_panel", "Educational Assistance"))
        self.cBox_purpose.setItemText(2, _translate("doc_panel", "Financial Assistance"))
        self.cBox_purpose.setItemText(3, _translate("doc_panel", "Medical Assistance"))
        self.cBox_purpose.setItemText(4, _translate("doc_panel", "Loan"))
        self.cBox_purpose.setItemText(5, _translate("doc_panel", "Motor Loan"))
        self.cBox_purpose.setItemText(6, _translate("doc_panel", "Local Employment"))
        self.cBox_purpose.setItemText(7, _translate("doc_panel", "Bank Requirements"))
        self.cBox_purpose.setItemText(8, _translate("doc_panel", "Police Clearance"))
        self.edit_row.setText(_translate("doc_panel", "Edit"))
        self.line_editbirthdate.setPlaceholderText(_translate("doc_panel", "Birthdate"))
        self.label_66.setText(_translate("doc_panel", "About Software:"))
        self.label_67.setText(_translate("doc_panel", "Document Processing Panel is a software that is used as a tool \n"
"for the Kiosk Software named Document Processing for Kiosk.\n"
"This software can receive some inputs from the Kiosk version\n"
"so that this software can; create a file requested by the\n"
"Kiosk user; Manage Accounts that are or will be able to use\n"
"the Kiosk version; edit the document\'s specified personnels\n"
"whenever there\'s a change; and edit document\'s prices."))
        self.label_68.setText(_translate("doc_panel", "However, if there is a file template needed to be changed,\n"
"you may need to rename the new file and paste it to the\n"
"folder where the old template was located.\n"
"\n"
"Click the \"MENU\" button above for the sidebar to appear.\n"
""))
        self.label_37.setText(_translate("doc_panel", "Document Prices Edit"))
        self.label_36.setText(_translate("doc_panel", "Certification for First Time Jobseeker Price:"))
        self.lineEdit.setPlaceholderText(_translate("doc_panel", "If the document is free, then put \"Free\". If not, include currency sign. Ex: Php. 50.00"))
        self.label_38.setText(_translate("doc_panel", "Business Permit Price:"))
        self.lineEdit_2.setPlaceholderText(_translate("doc_panel", "If the document is free, then put \"Free\". If not, include currency sign. Ex: Php. 50.00"))
        self.label_39.setText(_translate("doc_panel", "Barangay Clearance Price:"))
        self.lineEdit_3.setPlaceholderText(_translate("doc_panel", "If the document is free, then put \"Free\". If not, include currency sign. Ex: Php. 50.00"))
        self.edit_price.setText(_translate("doc_panel", "Edit"))
        self.label_53.setText(_translate("doc_panel", "Document Contents Edit"))
        self.label_54.setText(_translate("doc_panel", "Barangay Year: "))
        self.lineEdit_4.setPlaceholderText(_translate("doc_panel", "2xxx - 2yyy Ex: 2023-2025"))
        self.label_55.setText(_translate("doc_panel", "Barangay Captain: "))
        self.line_captain.setPlaceholderText(_translate("doc_panel", "Name of Barangay Captain"))
        self.label_57.setText(_translate("doc_panel", "Comm. on Health and Solid Waste: "))
        self.line_chsw.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_58.setText(_translate("doc_panel", "Comm. on Livelihood: "))
        self.line_livelihood.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_60.setText(_translate("doc_panel", "Comm. on Education & Beautification: "))
        self.line_ceb.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_59.setText(_translate("doc_panel", "Comm. on Peace and Order: "))
        self.line_cpo.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_61.setText(_translate("doc_panel", "Comm. on Social Services: "))
        self.line_css.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_62.setText(_translate("doc_panel", "Comm. on Sports & Youth Development: "))
        self.line_csyd.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_56.setText(_translate("doc_panel", "Comm. on Finance/ Comm. on Public Works: "))
        self.line_cfcp.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.label_63.setText(_translate("doc_panel", "Sk Chairman: "))
        self.line_skchairman.setPlaceholderText(_translate("doc_panel", "Name of Kagawad In Charge"))
        self.edit_doccontent.setText(_translate("doc_panel", "Edit"))
        item = self.tbl_accView.horizontalHeaderItem(0)
        item.setText(_translate("doc_panel", "Email"))
        item = self.tbl_accView.horizontalHeaderItem(1)
        item.setText(_translate("doc_panel", "Password"))
        item = self.tbl_accView.horizontalHeaderItem(2)
        item.setText(_translate("doc_panel", "Name"))
        item = self.tbl_accView.horizontalHeaderItem(3)
        item.setText(_translate("doc_panel", "Sex"))
        item = self.tbl_accView.horizontalHeaderItem(4)
        item.setText(_translate("doc_panel", "Address"))
        item = self.tbl_accView.horizontalHeaderItem(5)
        item.setText(_translate("doc_panel", "Birthdate"))
        item = self.tbl_accView.horizontalHeaderItem(6)
        item.setText(_translate("doc_panel", "Birthplace"))
        item = self.tbl_accView.horizontalHeaderItem(7)
        item.setText(_translate("doc_panel", "Civil Status"))
        item = self.tbl_accView.horizontalHeaderItem(8)
        item.setText(_translate("doc_panel", "Citizenship"))
        self.label_10.setText(_translate("doc_panel", "Edit Account Contents"))
        self.label_11.setText(_translate("doc_panel", "Email"))
        self.edit_email.setPlaceholderText(_translate("doc_panel", "Enter Email"))
        self.label_12.setText(_translate("doc_panel", "Password"))
        self.edit_password.setPlaceholderText(_translate("doc_panel", "Password"))
        self.label_13.setText(_translate("doc_panel", "Name"))
        self.edit_uname.setPlaceholderText(_translate("doc_panel", "Name"))
        self.label_14.setText(_translate("doc_panel", "Sex"))
        self.edit_usex.setPlaceholderText(_translate("doc_panel", "Sex"))
        self.label_17.setText(_translate("doc_panel", "Address"))
        self.edit_uaddress.setPlaceholderText(_translate("doc_panel", "Address"))
        self.label_15.setText(_translate("doc_panel", "Birthdate"))
        self.edit_ubday.setPlaceholderText(_translate("doc_panel", "Birthdate"))
        self.label_18.setText(_translate("doc_panel", "Birthplace"))
        self.edit_ubplace.setPlaceholderText(_translate("doc_panel", "Birthplace"))
        self.label_16.setText(_translate("doc_panel", "Civil Status"))
        self.edit_ucstatus.setPlaceholderText(_translate("doc_panel", "Civil Status"))
        self.label_19.setText(_translate("doc_panel", "Citizenship"))
        self.edit_ucitizenship.setPlaceholderText(_translate("doc_panel", "Citizenship"))
        self.edit_user.setText(_translate("doc_panel", "Edit User"))
        self.refresh_edittabel.setText(_translate("doc_panel", "Refresh"))
        self.line_searchbar.setPlaceholderText(_translate("doc_panel", "Enter Email"))
        item = self.tbl_forview.horizontalHeaderItem(0)
        item.setText(_translate("doc_panel", "Reference #"))
        item = self.tbl_forview.horizontalHeaderItem(1)
        item.setText(_translate("doc_panel", "Date Added"))
        item = self.tbl_forview.horizontalHeaderItem(2)
        item.setText(_translate("doc_panel", "Requested Doc"))
        item = self.tbl_forview.horizontalHeaderItem(3)
        item.setText(_translate("doc_panel", "Price"))
        item = self.tbl_forview.horizontalHeaderItem(4)
        item.setText(_translate("doc_panel", "Name"))
        item = self.tbl_forview.horizontalHeaderItem(5)
        item.setText(_translate("doc_panel", "Age"))
        item = self.tbl_forview.horizontalHeaderItem(6)
        item.setText(_translate("doc_panel", "Sex"))
        item = self.tbl_forview.horizontalHeaderItem(7)
        item.setText(_translate("doc_panel", "Address"))
        item = self.tbl_forview.horizontalHeaderItem(8)
        item.setText(_translate("doc_panel", "Requirements"))
        item = self.tbl_forview.horizontalHeaderItem(9)
        item.setText(_translate("doc_panel", "Birthdate"))
        item = self.tbl_forview.horizontalHeaderItem(10)
        item.setText(_translate("doc_panel", "Birthplace"))
        item = self.tbl_forview.horizontalHeaderItem(11)
        item.setText(_translate("doc_panel", "Civil Status"))
        item = self.tbl_forview.horizontalHeaderItem(12)
        item.setText(_translate("doc_panel", "Citizenship"))
        item = self.tbl_forview.horizontalHeaderItem(13)
        item.setText(_translate("doc_panel", "Purpose"))
        item = self.tbl_forview.horizontalHeaderItem(14)
        item.setText(_translate("doc_panel", "Business Name"))
        item = self.tbl_forview.horizontalHeaderItem(15)
        item.setText(_translate("doc_panel", "Business Address"))
        item = self.tbl_forview.horizontalHeaderItem(16)
        item.setText(_translate("doc_panel", "Years Stayed"))
        self.btn_create.setText(_translate("doc_panel", "Create File"))
        self.btn_filedir.setText(_translate("doc_panel", "Select File Directory"))
        self.btn_delete.setText(_translate("doc_panel", "Delete"))
        self.btn_refresh.setText(_translate("doc_panel", "Refresh"))
        self.label_4.setText(_translate("doc_panel", "Requirements Edit"))
        self.label_5.setText(_translate("doc_panel", "Reference #:"))
        self.line_ref.setPlaceholderText(_translate("doc_panel", "Enter Ref. #"))
        self.label_6.setText(_translate("doc_panel", "Req. Status:"))
        self.line_req.setPlaceholderText(_translate("doc_panel", "Fully Paid, etc."))
        self.btn_editreq.setText(_translate("doc_panel", "Edit Requirements"))
